### ISSUE TITLE
Better support for ssh'ing to localhost is needed

### ISSUE THREAD

**Issue by davidedelvento** [NCAR/Inception#7]
I've started an inception=login session on regular queue on Cheyenne, and I need to do some `ssh localhost` as follows:

```
csgteam@r9i2n34:~> ls -l /usr/lib64/python2.7/curses/__init__.pyc
-rw-r--r-- 1 root root 1553 Oct 29  2015 /usr/lib64/python2.7/curses/__init__.pyc
csgteam@r9i2n34:~> ssh localhost
csgteam@r9i2n34:~> ls -l /usr/lib64/python2.7/curses/
ls: cannot access /usr/lib64/python2.7/curses/: No such file or directory
csgteam@r9i2n34:~> exit
```

As you can see, the `ssh localhost` breaks something in inception and now I'm out of the container (at least disk-wise, I have not tested if I'm totally out of it).

This makes it much clunkier to use the kind of installs which I perform, which always require an ssh to localhost as a way to "clean" the environment.

**Comment by matthewsucar** [comment]
This is a function of how you structure your container and the environment around it. Inception doesn't know anything about ssh (nor should it -- ssh isn't even a contained process). That said, this actually works fine for me.

If the community has suggestions, I'd love to hear them, but in general there's not a way to steer people into a container once you leave the node (which is essentially what you're doing here). You need some IPC mechanism to know that a given connection is supposed to be contained and there's not a general way to do that. 

The way we have this setup on Cheyenne is that there's an environment variable (PBS_INCEPTION_IMAGE) that gets set when you request an alternate image. At various points in the job launch process and/or ssh, if that variable is set, inception gets called and your environment is container'ified (implemented through various unpublished ugly hacks).

So, when you tell pbs -l inception=login, a hook gets called which does a couple things:

1. Sets PBS_INCEPTION_IMAGE=login
2. Sets your PBS shell to /usr/local/bin/pbs_shell

When PBS finally launches your job, pbs_shell does some system specific crazy and calls inception with some standard flags if it sees PBS_INCEPTION_IMAGE set. Inception then looks up your shell and calls that inside the container. PBS thinks that you've launched a normal POSIX shell and does what it would normally do. 

If you ssh to another node, for example in a multi-node MPI job, or doing what you're doing here, as long as PBS_INCEPTION_IMAGE is set and your ssh client is configured to pass around PBS_INCEPTION_IMAGE, which it should be in the login container, you should get contained on the remote node. The ssh daemon on our compute nodes runs a script that (among other things) checks for PBS_INCEPTION_IMAGE and calls inception if it sees that set before it calls your shell. 

For remote launches via proprietary software, we also have a library that we can LD_PRELOAD which replaces the exec() family with something that behaves in a similar way. It's not very robust, and we're planning to phase it out. In the near term, this will be replaced by some PAM code which will cover all the cases that we care about. In particular, a PAM module should let us launch multi-node MPT jobs inside containers (now that SGI/HPE Array Services finally supports PAM). 

Obviously this is all a rather leaky abstraction, so there are a few ways you can break it:
- Tampering with PBS_INCEPTION_IMAGE will break it (or optionally, change the image that you get after an ssh call)
- Using a container that hasn't had the ssh config magic set to pass PBS_INCEPTION_IMAGE will break it completely (SendEnv PBS_INCEPTION_IMAGE needs to appear in /etc/ssh/ssh_config or, perhaps, .ssh/config)
  - The login images should have this (including the test one that I setup yesterday) but probably nothing else does. I should probably add that to the container setup procedure. 
- Remote access via something other than ssh or PBS won't work (yet, again, PAM module coming soon)
 - If PBS_INCEPTION_IMAGE is set in your environment, you'll get the container even if you don't want it
   - mitigated in a few easy to detect cases inside PBS, to allow for regular jobs to be submitted inside shareq jobs

I'm going to close this bug as a bug with Cheyenne's setup rather than Inception. If the community is interested in how all this works, I think we can do a wiki page or something. As far as your specific problem goes, let's talk out of band.
